# Site settings
title: Thymeless Treats Bakery
email: your-email@domain.com
url: https://btkircher.github.io/
description: "Savor the Moments, Taste the Thyme -- Thymeless Treats Bakery, Where Every Bite is Timelessly Delicious!"
keywords: "bakery, cleveland"
skills: "Cupcakes - Cookies - Treats"
meta_author: Kircher Brian

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
# color:
#   primary: 181818 # Keeping Dark gray as the primary color
#   primary-rgb: "24,24,24"
#   secondary: 8b8b8b # Changing secondary to a deeper gray for better contrast
#   secondary-dark: 606060 # Slightly lighter than primary but darker than secondary for additional contrast

color:
  primary: 93A299  # Sage green as the primary color
  primary-rgb: "147,162,153"
  secondary: FFFFF0  # Ivory white as the secondary color
  secondary-dark: B0C4B1  # Slightly lighter than primary but still in the sage family for additional contrast


# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Cleveland
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100094256522051
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: North Ridgeville, OH 44039

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
